#!/usr/bin/env python3
"""Draws the app icons.

Written by hand, with zlib and struct, so the repository has no image-editing dependency and the
icons can be regenerated by anyone who checks the project out. The mark is a receipt with a torn
bottom edge on the app's dark green.
"""

import struct
import zlib
from pathlib import Path

GREEN = (20, 83, 45)
CREAM = (250, 249, 246)
INK = (20, 83, 45)

OUT = Path(__file__).resolve().parent.parent / "public"


def png(path, size, pixels):
    raw = b"".join(b"\x00" + bytes(v for px in row for v in px) for row in pixels)
    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body))
    header = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


def draw(size, margin_ratio):
    """A receipt on green. `margin_ratio` leaves room for a maskable icon's safe zone."""
    pixels = [[GREEN for _ in range(size)] for _ in range(size)]

    margin = int(size * margin_ratio)
    left, right = margin, size - margin
    top, bottom = margin, size - margin
    width = right - left
    tooth = max(2, width // 10)

    for y in range(top, bottom):
        for x in range(left, right):
            # The bottom edge is torn into teeth, like a receipt off a roll.
            if y > bottom - tooth:
                phase = ((x - left) % (tooth * 2)) - tooth
                if abs(phase) < (y - (bottom - tooth)):
                    continue
            pixels[y][x] = CREAM

    # Printed lines. The last one is short, the way a total sits alone at the end.
    line_height = max(2, size // 32)
    gap = line_height * 3
    y = top + gap
    index = 0
    while y + line_height < bottom - tooth * 2:
        length = width - gap if index % 3 != 2 else width // 2
        for yy in range(y, y + line_height):
            for xx in range(left + gap // 2, left + gap // 2 + length - gap // 2):
                if 0 <= yy < size and 0 <= xx < size:
                    pixels[yy][xx] = INK
        y += gap
        index += 1

    return pixels


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for size, name, margin in [
        (192, "icon-192.png", 0.18),
        (512, "icon-512.png", 0.18),
        # A maskable icon may be cropped to a circle, so the mark sits well inside the edge.
        (512, "icon-512-maskable.png", 0.28),
        (180, "apple-touch-icon.png", 0.18),
        (32, "favicon-32.png", 0.14),
    ]:
        png(OUT / name, size, draw(size, margin))
        print("wrote", name)


if __name__ == "__main__":
    main()
